### ISSUE TITLE
Broken PURLs in CHIRO

### ISSUE THREAD

**Issue by matentzn** [obophenotype/chiro#22]
Hey! In our great [OBO wide effort to fix our PURLs](https://github.com/orgs/OBOFoundry/projects/5), I noticed the following wrong ones being used in CHIRO:

- [x] http://purl.obolibrary.org/NCBITaxon_2 (should be: http://purl.obolibrary.org/obo/NCBITaxon_2)
- [x] http://purl.obolibrary.org/GO_0016088
- [x] http://purl.obolibrary.org/GO_0003824
- [x] http://purl.obolibrary.org/GO_0003809

**Comment by nicolevasilevsky** [comment]
http://purl.obolibrary.org/NCBITaxon_2 looks like it is a duplicate, so I obsoleted it.
